/**
 * Visual Math Diagram Types
 *
 * Type definitions for structured diagram data generated by GPT-4o
 * and rendered by React/SVG components.
 */

// =============================================================================
// Diagram Type Union
// =============================================================================

export type DiagramType =
  | 'bar-model'
  | 'number-line'
  | 'fraction-visual'
  | 'array-grid';

// =============================================================================
// Bar Model Types (Singapore Math, Common Core tape diagrams)
// =============================================================================

export interface BarModelPart {
  /** Numeric value or '?' for unknown */
  value: number | '?';
  /** Optional label for this part */
  label?: string;
  /** CSS color (defaults provided by component) */
  color?: string;
}

export interface BarModelData {
  /** Layout style:
   * - part-whole: single bar with segments side-by-side
   * - comparison: two parallel bars for comparing quantities
   * - stacked: Singapore Math style with each item as a separate row (recommended for word problems)
   */
  layout: 'part-whole' | 'comparison' | 'stacked';
  /** Total value (null if unknown/to be calculated) */
  total?: number | null;
  /** The parts that make up the bar(s) */
  parts: BarModelPart[];
  /** Index of the unknown part (0-indexed) */
  unknownIndex?: number;
  /** Optional labels */
  labels?: {
    total?: string;
    parts?: string[];
  };
}

// =============================================================================
// Number Line Types
// =============================================================================

export interface NumberLinePoint {
  /** Value on the number line */
  value: number;
  /** Label to display at this point */
  label?: string;
  /** Whether to visually highlight this point */
  highlight?: boolean;
  /** Position of label relative to point */
  position?: 'above' | 'below';
}

export interface NumberLineJump {
  /** Starting value of the jump */
  from: number;
  /** Ending value of the jump */
  to: number;
  /** Label for the jump (e.g., "+5") */
  label?: string;
  /** CSS color for the jump arrow */
  color?: string;
}

export interface NumberLineData {
  /** Minimum value (left end) */
  min: number;
  /** Maximum value (right end) */
  max: number;
  /** Interval between tick marks (auto-calculated if omitted) */
  tickInterval?: number;
  /** Points to plot on the line */
  points: NumberLinePoint[];
  /** Jump arrows showing operations */
  jumps?: NumberLineJump[];
}

// =============================================================================
// Fraction Visual Types
// =============================================================================

export interface FractionItem {
  /** Numerator of the fraction */
  numerator: number;
  /** Denominator of the fraction */
  denominator: number;
  /** Number of parts to shade (defaults to numerator) */
  shaded?: number;
  /** Optional label for this fraction */
  label?: string;
  /** CSS color for shaded parts */
  color?: string;
}

export interface FractionVisualData {
  /** Display type: circle (pie) or strip (bar) */
  type: 'circle' | 'strip';
  /** One or more fractions to display */
  fractions: FractionItem[];
  /** Whether to show fractions side-by-side for comparison */
  showComparison?: boolean;
}

// =============================================================================
// Array Grid Types (Multiplication)
// =============================================================================

export interface ArrayGridData {
  /** Number of rows */
  rows: number;
  /** Number of columns */
  columns: number;
  /** Visual style for objects */
  objectStyle?: 'dot' | 'square';
  /** Row to highlight (1-indexed) */
  highlightRow?: number;
  /** Column to highlight (1-indexed) */
  highlightColumn?: number;
  /** Whether to show total count */
  showTotal?: boolean;
  /** Label (e.g., "3 × 4 = 12") */
  label?: string;
}

// =============================================================================
// Diagram Data Wrapper
// =============================================================================

/**
 * Union type for all diagram data
 */
export type DiagramDataUnion =
  | BarModelData
  | NumberLineData
  | FractionVisualData
  | ArrayGridData;

/**
 * Complete diagram data with type discriminator and required fallback
 */
export interface DiagramData {
  /** The diagram type - determines which component renders it */
  type: DiagramType;
  /** Type-specific data */
  data: DiagramDataUnion;
  /** REQUIRED: Human-readable text description for fallback */
  textFallback: string;
}

// =============================================================================
// Type Guards
// =============================================================================

export function isBarModelData(data: DiagramDataUnion): data is BarModelData {
  return 'layout' in data && 'parts' in data;
}

export function isNumberLineData(data: DiagramDataUnion): data is NumberLineData {
  return 'min' in data && 'max' in data && 'points' in data;
}

export function isFractionVisualData(data: DiagramDataUnion): data is FractionVisualData {
  return 'type' in data && 'fractions' in data && (data.type === 'circle' || data.type === 'strip');
}

export function isArrayGridData(data: DiagramDataUnion): data is ArrayGridData {
  return 'rows' in data && 'columns' in data;
}

// =============================================================================
// Validation Helpers
// =============================================================================

/**
 * Validate that diagram data is well-formed
 */
export function validateDiagramData(diagram: DiagramData | null | undefined): boolean {
  if (!diagram) return false;
  if (!diagram.type || !diagram.data || !diagram.textFallback) return false;

  const supportedTypes: DiagramType[] = ['bar-model', 'number-line', 'fraction-visual', 'array-grid'];
  if (!supportedTypes.includes(diagram.type)) return false;

  switch (diagram.type) {
    case 'bar-model':
      return isBarModelData(diagram.data) && diagram.data.parts.length > 0;
    case 'number-line':
      return isNumberLineData(diagram.data) && diagram.data.min < diagram.data.max;
    case 'fraction-visual':
      return (
        isFractionVisualData(diagram.data) &&
        diagram.data.fractions.length > 0 &&
        diagram.data.fractions.every(f => f.denominator > 0)
      );
    case 'array-grid':
      return isArrayGridData(diagram.data) && diagram.data.rows > 0 && diagram.data.columns > 0;
    default:
      return false;
  }
}

// =============================================================================
// Default Colors
// =============================================================================

export const DIAGRAM_COLORS = {
  primary: '#60A5FA',    // blue-400
  secondary: '#34D399',  // emerald-400
  tertiary: '#FBBF24',   // amber-400
  quaternary: '#F87171', // red-400
  quinary: '#A78BFA',    // violet-400
  unknown: '#9CA3AF',    // gray-400
  highlight: '#FCD34D',  // amber-300
  stroke: '#374151',     // gray-700
  strokeLight: '#9CA3AF', // gray-400
  fill: '#F3F4F6',       // gray-100
  fillDark: '#1F2937',   // gray-800
};

export const DIAGRAM_COLOR_PALETTE = [
  DIAGRAM_COLORS.primary,
  DIAGRAM_COLORS.secondary,
  DIAGRAM_COLORS.tertiary,
  DIAGRAM_COLORS.quaternary,
  DIAGRAM_COLORS.quinary,
];
